# Generated by Django 2.0.9 on 2018-12-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
