# Generated by Django 2.0.9 on 2019-01-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0002_auto_20181223_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
