# Generated by Django 2.0.9 on 2019-01-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_auto_20190105_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
