# Generated by Django 2.0.9 on 2019-01-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_auto_20190105_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='drink',
            field=models.ManyToManyField(blank=True, null=True, to='pizzeria.Drink'),
        ),
    ]
