# Generated by Django 2.1.5 on 2019-01-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0005_auto_20190105_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2010-10-10'),
            preserve_default=False,
        ),
    ]
