# Generated by Django 2.1.5 on 2019-01-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0006_auto_20190105_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
