# Generated by Django 2.1.5 on 2019-01-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0007_pizza_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
