# Generated by Django 2.1.5 on 2019-01-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0008_auto_20190106_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='total_price',
        ),
    ]
